config/routes.rb
Rails.application.routes.draw do
  
    root to: 'tasks#index'
    resources :tasks
    
    get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'
    resources :users, only: [:new, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :content, presence: true, length: { maximum: 255 }
    validates :status, presence: true, length: { maximum: 10 }
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     include SessionsHelper
    private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to login_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only:[:show,:edit,:update,:destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  def index
      if logged_in?
        @tasks = current_user.tasks
      end
  end

  def show 
  end

  def new
      @task = Task.new
  end

  def create
      @task = current_user.tasks.build(task_params)
      
      if @task.save
          flash[:success] = 'Taskが正常に投稿されました'
          redirect_to @task
      else
          flash.now[:danger] = 'Taskが投稿されませんでした'
          render :new
      end
  end

  def edit
  end

  def update
      if @task.update(task_params)
          flash[:success] = 'Taskは正常に更新されました'
          redirect_to @task
      else
          flash.now[:danger] = 'Taskは正常に更新されませんでした'
          render :edit
      end
  end

  def destroy
      @task.destroy
      
      flash[:success] = 'Taskは正常に消去されました'
      redirect_to tasks_url
  end
  
  private
  
  def set_task
    @task = Task.find(params[:id])
  end
  
  def task_params
      params.require(:task).permit(:content, :status)
  end
  
  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      redirect_to login_url
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to login_url
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_tasks.html.erb
<% flash.each do |task_type, task| %>

<div>
    <%= task %>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TasklistApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      
      <%= render 'layouts/flash_tasks' %>
      
    <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |f| %>

<% if task.errors.any? %>

    <div id="error_explanation">
      <ul>
        
<% task.errors.full_messages.each do |msg| %>

          <li>
<%= msg %>
</li>
    
<% end %>

      </ul>
    </div>
  
<% end %>

<%= f.label :status, 'ステータス' %>

  
<%= f.text_field :status %>


  
<%= f.label :content, 'タスク' %>

  
<%= f.text_field :content %>


  
<%= f.submit '投稿' %>

<% end %>

app/views/tasks/edit.html.erb
<h1>id: 
<%= @task.id %>
 のタスク編集ページ</h1>

<%= render 'form', task: @task %>


<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<ul>
    
<% @tasks.each do |task| %>
<li>
    <%= link_to task.id, task %>
    
    <%= task.status %>
    &gt; 
    <%= task.content %>
</li>

<% end %>
    
</ul>

<%= link_to '新規タスクの投稿', new_task_path %>

<ul style="list-style:none;">
    <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
</ul>

app/views/tasks/new.html.erb
<h1>タスク新規作成ページ</h1>

<%= render 'form', task: @task %>

<%= link_to '一覧に戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>id:
<%= @task.id %>
のタスク詳細ページ</h1>

<p>ステータス:
<%= @task.status %>
</p>

<p>タスク:
<%= @task.content %>
</p>

<%= link_to '一覧に戻る', tasks_path %>

<%= link_to 'このタスクを編集する', edit_task_path(@task) %>

<%= link_to 'このタスクを消去する', @task, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %>

app/views/users/_form.html.erb
<div>
  <div>

    
<%= form_with(model: @user, local: true) do |f| %>

<% if user.errors.any? %>

    <div id="error_explanation">
      <ul>
        
<% user.errors.full_messages.each do |msg| %>

          <li>
<%= msg %>
</li>
    
<% end %>

      </ul>
    </div>
  
<% end %>

      
      <div>
        
<%= f.label :name, 'Name' %>

        
<%= f.text_field :name %>

      </div>

      <div>
        
<%= f.label :email, 'Email' %>

        
<%= f.email_field :email %>

      </div>

      <div>
        
<%= f.label :password, 'Password' %>

        
<%= f.password_field :password %>

      </div>

      <div>
        
<%= f.label :password_confirmation, 'Confirmation' %>

        
<%= f.password_field :password_confirmation %>

      </div>

      
<%= f.submit 'Sign up' %>

    
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div>
    <h1>Sign up</h1>
</div>



<%= render 'form', user: @user %>

<%= link_to 'login now!', login_url %>

  </div>
</div>